apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toxic-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jk105jk105/Toxic-CICD.git 
    targetRevision: HEAD
    path: app
  destination: 
    server: https://kubernetes.default.svc
    namespace: toxic

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

