apiVersion: v1
kind: Secret
metadata:
  name: registrykey
data:
  # For demo only. Thie is a fake value
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFzZGprbGpmYUdLSmJoamtna3NkamtiY3NKZmphc2xkaGtZbHBVd3pjWFpNYnpsMFlHRT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
